name: PicACG Sign In

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  sign-in:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: node picacg/sign-in.js
        env:
          SECRETS: ${{ toJSON(secrets) }}
